// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelErrorResponse model error response
//
// swagger:model model.ErrorResponse
type ModelErrorResponse struct {

	// error
	Error string `json:"error,omitempty"`
}

// Validate validates this model error response
func (m *ModelErrorResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model error response based on context it is used
func (m *ModelErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelErrorResponse) UnmarshalBinary(b []byte) error {
	var res ModelErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
